### ISSUE TITLE
Data wire

### ISSUE THREAD

**Issue by khan-pog** [MaltWhiskey/Mega-Cube#5]
Hello, sorry for the ignorant question however here it is. Would it be okay to use 0.7mm wire as a data single wire? (I have a lot of 0.7mm wire)

**Comment by MaltWhiskey** [comment]
From a signal standpoint it doesn’t matter. I used .22mm and .20mm because any thinner would break easily. But I recommend as thin as possible because it will obstruct the view through the cube a bit.


Op 1 jan. 2022 om 15:47 heeft khan-pog ***@***.***> het volgende geschreven:

﻿

Hello, sorry for the ignorant question however here it is. Would it be okay to use 0.7mm wire as a data single wire? (I have a lot of 0.7mm wire)
