### ISSUE TITLE
Affiliate links

### ISSUE THREAD

**Issue by brandonfake69** [MaltWhiskey/Mega-Cube#7]
I understand you don't want to provide a kit (given the huge upfront investment in the items you'd have to make) but I'd still love to get a more detailed list of items since I am quite new to the hardware stuff. On AliExpress, for instance, there are a lot of results for "pl9823". Have you considered adding affiliate links to this repo (and your YouTube channel)? At ~$400 USD for just the lights you could make a killing since people would buy stuff to make for not just this but other projects they have in mind (AliExpress has an affiliate program that pays 9%). I'd certainly buy through your links since you've been kind enough to provide this repo and videos. You could also link to the power supplies, wire, acrylic (I'd even buy a pre-made acrylic box if you link to one), the filament used to make the 3d printed parts, etc. 

EDIT: I think you should put all of this links in the README.md so it's easy for people to find. You can even include links for the soldering iron, mat, wire, solder, wire cutters/crimpers, your 3d printer, etc. that you use since I don't have a lot of that stuff. Even if I don't intend to build a massive cube for my first project this helps out a newb like myself on the tools to get.

Thanks!

**Comment by MaltWhiskey** [comment]
Hi Brandon?There quite a few people that made or are making my cube, so that affiliate linking may no be such a bad thing, considering it’ll help people finding the right stuff… I’ll look into it.I found some cheaper led’s than the PL9823 also more energy efficient. I have used these so i can recommend them. Here is a non affiliated link for you:https://a.aliexpress.com/_EGUFXldKind Regards,DaniëlOp 20 aug. 2023 om 03:01 heeft brandonfake69 ***@***.***> het volgende geschreven:﻿
I understand you don't want to provide a kit (given the huge upfront investment in the items you'd have to make) but I'd still love to get a more detailed list of items since I am quite new to the hardware stuff. On AliExpress, for instance, there are a lot of results for "pl9823". Have you considered adding affiliate links to this repo (and your YouTube channel)? At ~$400 USD for just the lights you could make a killing (AliExpress has an affiliate program that pays 9%). I'd certainly buy through your links since you've been kind enough to provide this repo and videos. You could also link to the power supplies, wire, acrylic (I'd even buy a pre-made box if you link to one), the filament used to make the 3d printed parts, etc.
Thanks!

**Comment by devoh747** [comment]
The link to the LEDs didn't work for me.

**Comment by brandonfake69** [comment]
There's a missing space. Just remove the "Kind" from the end of the URL.

**Comment by brandonfake69** [comment]
Hi,
Any progress on this? I’d love to get started and give you some of that sweet sweet affiliate revenue. I tested the top hat LEDs you linked to and they seem to work great. Also, I thought I saw a comment on one of your videos about using resistors but I couldn’t see where they were used. What value and how many did you use?

**Comment by MaltWhiskey** [comment]
I signed up for the affiliate program, but decided not to use it. The reason is the suppliers that i would recommend are not part of the affiliate program. So i can't generate affiliate links for them. There are suppliers that are in the affiliate program, but they are a lot more expensive and if i wouldn't buy from them myself i can't recommend them.

There are resistors on the pcb (the real one, not the 3d printed), the values/components are in the assembly file. No need to worry about them unless you make the wires to the led channels a lot longer. They are needed to suppress transients and reflections.

**Comment by Althepeoplespal** [comment]
Do you recommend the round or hat version of the WS2811 leds? Are there any other changes or updates that you've done to this project that may help while I'm in the planning stages of building this cube?

**Comment by Pax-IT** [comment]
Because I'm late to the party, the link: https://a.aliexpress.com/_EGUFXld does not work anymore, I'm also looking which LEDs you used. Is it possible you update your README.md and at the parts you used, not links but types and other numbers that can be helpful? 

And maybe to get some revenue add a buy me coffee or patreon link.
